config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :posts do
    resources :comments
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <div>
            </div>

            <% if current_user %>
            <p>Logged in as <%= current_user.first_name %></p>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li> <%= link_to "Home", posts_path %></li>
              <li> <%= link_to "Add a New Post", new_post_url %></li>
              <li> <%= link_to "Delete Post", @post, method: :delete, data: {confirm: "Do you want to destory this post for ever and ever?"} %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %> </li>
            </ul>
          </div>

          <% else %>
          <p><%= link_to "Log In", new_user_session_path %>  | <%= link_to "Sign Up", new_user_registration_path %></p>
          <% end %>
        </div>
      </nav>
    </div>
  </div>




  <div class="jumbotron">
    <h1>welcome to the <span class="codemoji">codemoji</span?</h1>
    </div>

  <div class="alerts">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

    <%= yield %>



  </body>
  </html>